[platformio]
src_dir = source

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<mega/> -<esp32/>
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<esp32/> -<mega/>
monitor_speed = 115200
lib_deps =